export enum LocIds {
  EditorTitle = 'editor-title',
  RefreshScreen = 'refresh-screen',
  WaypointManager = 'waypoint-manager',
  WindManager = 'wind-manager',
  ToggleDepthMap = 'toggle-depth-map',
  RedrawsTheMapContentsOnScreen = 'redraws-the-map-contents-on-screen',
  EditPlayerAndAIWaypoints = 'edit-player-and-ai-waypoints',
  EditWindPositionsDirectionsAndStrengths = 'edit-wind-positions-directions-and-strengths',
  TheEditorShowsTheColormapOrHeightmapOfTheMap = 'the-editor-shows-the-colormap-or-heightmap-of-the-map',
  ZoomControl = 'zoom-control',
  SwitchToTheme = 'switch-to-theme',
  SettingsWereSavedSuccessfully = 'settings-were-saved-successfully',
  AnErrorOccurredWhileSavingTheSettings = 'an-error-occurred-while-saving-the-settings',
  FailedToSaveSettings = 'failed-to-save-settings',
  FailedToLoadSettings = 'failed-to-load-settings',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
  Reset = 'reset',
  ZoomValue = 'zoom-value',
  Language = 'language',
  Unknown = 'unknown',
}
