export enum MenuItemIds {
  ToggleDepthMap = 'toggle_depth_map',
  NewMission = 'new_mission',
  FileOpen = 'file_open',
  CloseMission = 'close_mission',
  SaveMission = 'save_mission',
  ExportMission = 'export_mission',
  EditMission = 'edit_mission',
  ExportMissionData = 'export_mission_data',
  ZoomIn = 'zoom_in',
  ZoomOut = 'zoom_out',
  Reset = 'reset',
  RedrawScreen = 'redraw_screen',
  Unknown = 'unknown',
}
